baseurl: /pythonic

collections:
  articles:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"

exclude: [README.md, Gemfile]